nav:
  - title: Wir
    dropdown:
      - title: News
        url: news

      - title: Referenzen
        url: references

      - title: Über uns
        url: about
        
      - title: Unsere Partner
        url: our_partners

      - title: Kontakt & Impressum
        url:  contact_imprint

      - title: Kontakt & Impressum
        url:  contact_imprint

  - title: bringen
    dropdown: 
      - title: Veranstaltungsmanagement
        url: business_intellegence

      - title: Facillity Management
        url: facility_management

      - title: Business Management
        url: business_intellegence

      - title: Hosting
        url: hosting

      - title: Dienstleistungen
        url: services

  - title: Lösungen
    dropdown:
      - title: Facillity Management
        url: facility_management

      - title: Events % Locations
        url: event_locations

      - title: Konzerthäuser
        url: concert_halls

      - title: Orchester & Ensembles
        url: orchestras_ensembles

      - title: Festivals & Veranstalter
        url: festivals_promoters
  
banner: 

  - title: BESONDERE ORTE Berlin Umweltforum GmbH
    text: evis ist das zentrale Werkzeug für die Organisation unserer Arbeitsabläufe. Ohne das in evis abgebildete Wissen könnten wir die knapp 1.000 Veranstaltungen, die pro Saison im Wiener Konzerthaus stattfinden, nicht planen, vorbereiten und durchführen. Dass wir mit evis über ein mächtiges, allen im Haus zugängliches Wissenstool verfügen, hat uns auch bei der Zertifizierung unseres Betriebes nach ISO 9001-2015 sehr geholfen – evis ist nicht zuletzt ein Werkzeug für aktives Qualitätsmanagement.
    img-url: /assets/img/banner/banner_wien.png

  - title: Lol
    text: evis ist das zentrale Werkzeug für die Organisation unserer Arbeitsabläufe. Ohne das in evis abgebildete Wissen könnten wir die knapp 1.000 Veranstaltungen, die pro Saison im Wiener Konzerthaus stattfinden, nicht planen, vorbereiten und durchführen. Dass wir mit evis über ein mächtiges, allen im Haus zugängliches Wissenstool verfügen, hat uns auch bei der Zertifizierung unseres Betriebes nach ISO 9001-2015 sehr geholfen – evis ist nicht zuletzt ein Werkzeug für aktives Qualitätsmanagement.
    img-url: /assets/img/banner/bob_franzoesische_friedrichstadtkirche_inside.png

footer:

  - title: Warum wir?
    content: 
      - title: Über uns
        url: about_us
      
      - title: Technologie
        url: technology

  - title: Zielgruppen
    content: 
      - title: Veranstaltungsbetriebe
        url: ""

      - title: Konzerthäuser
        url: ""

      - title: Orchester
        url: ""

      - title: Festivals
        url: ""

      - title: Facillity Managements
        url: ""

      - title: Serverhosting
        url: ""

  - title: Module
    content: 
      - title: Veranstaltungs- und Raummanagement
        url: ""

      - title: Vermietung
        url: ""

      - title: Adress- und Kontaktmanagement
        url: ""

      - title: Marketing-Tools
        url: ""

      - title: Werke, Interpreten, Noten & Instrumente
        url: ""

      - title: Orchestermanagement
        url: ""
      
      - title: Kalkulation, Budgetierung & Controlling
        url: ""

      - title: Mobile Applications
        url: ""

      - title: Facillity Management
        url: ""

      - title: Serverhosting
        url: ""

  - title: Kontakt
    content: 
      - title: Kontaktieren Sie uns
        url: ""
